# -*- coding: utf-8 -*-
"""
Syncs Vedic images generated by Google Imagen from the artifact directory 
into the appropriate production chapter visual folders.
Supports Chapter 5 (42 shots) and Chapter 8 (35 shots).
"""

import sys
import shutil
from pathlib import Path

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

ARTIFACT_DIR = Path(r"C:\Users\Shishyan\.gemini\antigravity\brain\3487bd75-58a3-46ff-b8c8-f0b8c719cf46")
PRODUCTION_VISUALS = Path(r"C:\GitHub\Gurukuladesam\production\visuals\thirukkural")

# Mapping pattern: (prefix_in_artifact_name, relative_destination_path)
MAPPINGS = {
    # Chapter 5: இல்வாழ்க்கை (42 shots)
    "ch05_01_n01": "05-ilvaazhkkai/01-n01_grihastha_morning_lamp.jpg",
    "ch05_02_n02": "05-ilvaazhkkai/02-n02_welcoming_wandering_students.jpg",
    "ch05_03_n03": "05-ilvaazhkkai/03-n03_serving_wandering_mendicants.jpg",
    "ch05_04_n04": "05-ilvaazhkkai/04-n04_tending_elderly_kinsmen.jpg",
    "ch05_05_n05": "05-ilvaazhkkai/05-n05_feeding_weary_travelers.jpg",
    "ch05_06_n06": "05-ilvaazhkkai/06-n06_giving_shelter_in_monsoon.jpg",
    "ch05_07_n07": "05-ilvaazhkkai/07-n07_distribution_of_grain.jpg",
    "ch05_08_n08": "05-ilvaazhkkai/08-n08_comforting_lonely_elder.jpg",
    "ch05_09_n09": "05-ilvaazhkkai/09-n09_ancestral_libations_river.jpg",
    "ch05_10_n10": "05-ilvaazhkkai/10-n10_temple_flower_garlanding.jpg",
    "ch05_11_n11": "05-ilvaazhkkai/11-n11_honoring_visiting_kinsfolk.jpg",
    "ch05_12_n12": "05-ilvaazhkkai/12-n12_communal_evening_prayer.jpg",
    "ch05_13_n13": "05-ilvaazhkkai/13-n13_measuring_honest_produce.jpg",
    "ch05_14_n14": "05-ilvaazhkkai/14-n14_sharing_evening_meal.jpg",
    "ch05_15_n15": "05-ilvaazhkkai/15-n15_refusing_unjust_gain.jpg",
    "ch05_16_n16": "05-ilvaazhkkai/16-n16_everlasting_lineage_of_honor.jpg",
    "ch05_17_n17": "05-ilvaazhkkai/17-n17_husband_wife_planting_tree.jpg",
    "ch05_18_n18": "05-ilvaazhkkai/18-n18_mutual_respect_in_counsel.jpg",
    "ch05_19_n19": "05-ilvaazhkkai/19-n19_cradle_under_jasmine_arbor.jpg",
    "ch05_20_n20": "05-ilvaazhkkai/20-n20_tender_care_of_infant.jpg",
    "ch05_21_n21": "05-ilvaazhkkai/21-n21_grihastha_meditating_at_home.jpg",
    "ch05_22_n22": "05-ilvaazhkkai/22-n22_ascetic_visiting_virtuous_home.jpg",
    "ch05_23_n23": "05-ilvaazhkkai/23-n23_blooming_sacred_tulsi_thara.jpg",
    "ch05_24_n24": "05-ilvaazhkkai/24-n24_pure_domestic_altar.jpg",
    "ch05_25_n25": "05-ilvaazhkkai/25-n25_householder_guiding_villagers.jpg",
    "ch05_26_n26": "05-ilvaazhkkai/26-n26_sustaining_community_reservoir.jpg",
    "ch05_27_n27": "05-ilvaazhkkai/27-n27_weaving_cloth_for_monks.jpg",
    "ch05_28_n28": "05-ilvaazhkkai/28-n28_harvesting_medicinal_herbs.jpg",
    "ch05_29_n29": "05-ilvaazhkkai/29-n29_teaching_children_values.jpg",
    "ch05_30_n30": "05-ilvaazhkkai/30-n30_supporting_pilgrims_road.jpg",
    "ch05_31_n31": "05-ilvaazhkkai/31-n31_reconciling_quarreling_neighbors.jpg",
    "ch05_32_n32": "05-ilvaazhkkai/32-n32_lamp_lit_at_village_crossroads.jpg",
    "ch05_33_n33": "05-ilvaazhkkai/33-n33_bountiful_paddy_threshing.jpg",
    "ch05_34_n34": "05-ilvaazhkkai/34-n34_distributing_first_harvest.jpg",
    "ch05_35_n35": "05-ilvaazhkkai/35-n35_clean_home_rangoli_threshold.jpg",
    "ch05_36_n36": "05-ilvaazhkkai/36-n36_harmonious_evening_meal.jpg",
    "ch05_37_n37": "05-ilvaazhkkai/37-n37_revered_elder_householder.jpg",
    "ch05_38_n38": "05-ilvaazhkkai/38-n38_celestial_glow_over_courtyard.jpg",
    "ch05_39_n39": "05-ilvaazhkkai/39-n39_jasmine_petals_floating_water.jpg",
    "ch05_40_n40": "05-ilvaazhkkai/40-n40_sunlit_homestead_orchard.jpg",
    "ch05_41_n41": "05-ilvaazhkkai/41-n41_householder_looking_at_horizon.jpg",
    "ch05_42_n42": "05-ilvaazhkkai/42-n42_eternal_temple_gateway_dusk.jpg",

    # Chapter 8: அன்புடைமை (35 shots)
    "ch08_01_n01": "08-anbudaimai/01-n01_tears_of_joy_mother_child.jpg",
    "ch08_02_n02": "08-anbudaimai/02-n02_reunion_of_parted_friends.jpg",
    "ch08_03_n03": "08-anbudaimai/03-n03_tender_care_of_injured_bird.jpg",
    "ch08_04_n04": "08-anbudaimai/04-n04_weeping_for_another_sorrow.jpg",
    "ch08_05_n05": "08-anbudaimai/05-n05_miser_hoarding_in_darkness.jpg",
    "ch08_06_n06": "08-anbudaimai/06-n06_generous_giver_offering_all.jpg",
    "ch08_07_n07": "08-anbudaimai/07-n07_heroic_sacrifice_saving_fellows.jpg",
    "ch08_08_n08": "08-anbudaimai/08-n08_circle_of_friends_under_tree.jpg",
    "ch08_09_n09": "08-anbudaimai/09-n09_shared_labor_in_paddy_field.jpg",
    "ch08_10_n10": "08-anbudaimai/10-n10_elders_sharing_pan_and_laughter.jpg",
    "ch08_11_n11": "08-anbudaimai/11-n11_pacing_veranda_awaiting_friend.jpg",
    "ch08_12_n12": "08-anbudaimai/12-n12_warm_embrace_of_companions.jpg",
    "ch08_13_n13": "08-anbudaimai/13-n13_gift_of_fresh_lotus_garland.jpg",
    "ch08_14_n14": "08-anbudaimai/14-n14_playful_family_under_mango_boughs.jpg",
    "ch08_15_n15": "08-anbudaimai/15-n15_serene_transcendent_peace.jpg",
    "ch08_16_n16": "08-anbudaimai/16-n16_evening_cradle_lullaby.jpg",
    "ch08_17_n17": "08-anbudaimai/17-n17_forgiving_reformed_thief.jpg",
    "ch08_18_n18": "08-anbudaimai/18-n18_reconciling_feuding_tribes.jpg",
    "ch08_19_n19": "08-anbudaimai/19-n19_healing_a_bitter_heart.jpg",
    "ch08_20_n20": "08-anbudaimai/20-n20_boneless_worm_in_scorching_sun.jpg",
    "ch08_21_n21": "08-anbudaimai/21-n21_miserable_loneliness_of_unloving.jpg",
    "ch08_22_n22": "08-anbudaimai/22-n22_withering_barren_desert_tree.jpg",
    "ch08_23_n23": "08-anbudaimai/23-n23_dry_stump_in_rocky_ground.jpg",
    "ch08_24_n24": "08-anbudaimai/24-n24_hopeless_striving_without_affection.jpg",
    "ch08_25_n25": "08-anbudaimai/25-n25_contrast_of_lush_oasis.jpg",
    "ch08_26_n26": "08-anbudaimai/26-n26_handsome_exterior_cold_eyes.jpg",
    "ch08_27_n27": "08-anbudaimai/27-n27_humble_ragged_man_overflowing_love.jpg",
    "ch08_28_n28": "08-anbudaimai/28-n28_sculpting_the_hollow_statue.jpg",
    "ch08_29_n29": "08-anbudaimai/29-n29_vibrant_living_pulse_of_love.jpg",
    "ch08_30_n30": "08-anbudaimai/30-n30_hollow_skeleton_clad_in_skin.jpg",
    "ch08_31_n31": "08-anbudaimai/31-n31_child_running_into_open_arms.jpg",
    "ch08_32_n32": "08-anbudaimai/32-n32_sacred_flame_of_the_loving_heart.jpg",
    "ch08_33_n33": "08-anbudaimai/33-n33_village_celebrating_in_unity.jpg",
    "ch08_34_n34": "08-anbudaimai/34-n34_sunset_over_placid_lotus_lake.jpg",
    "ch08_35_n35": "08-anbudaimai/35-n35_morning_sunlight_illuminating_lovers.jpg",

    # Chapter 16 (Poraiyudaimai)
    "ch16_01_n01": "16-poraiyudaimai/01-n01_earth_bearing_diggers_plow.jpg",
    "ch16_02_n02": "16-poraiyudaimai/02-n02_quarrymen_hewing_mountain.jpg",
    "ch16_03_n03": "16-poraiyudaimai/03-n03_sage_hearing_harsh_abuse.jpg",
    "ch16_04_n04": "16-poraiyudaimai/04-n04_deep_well_yielding_sweet_water.jpg",
    "ch16_05_n05": "16-poraiyudaimai/05-n05_serene_monk_under_banyan.jpg",
    "ch16_06_n06": "16-poraiyudaimai/06-n06_fertile_delta_after_digging.jpg",
    "ch16_07_n07": "16-poraiyudaimai/07-n07_releasing_written_grievance.jpg",
    "ch16_08_n08": "16-poraiyudaimai/08-n08_embracing_former_slanderer.jpg",
    "ch16_09_n09": "16-poraiyudaimai/09-n09_writing_insult_on_sand_washed_by_wave.jpg",
    "ch16_10_n10": "16-poraiyudaimai/10-n10_gentle_smile_erasing_past_pain.jpg",
    "ch16_11_n11": "16-poraiyudaimai/11-n11_flowing_river_carrying_debris.jpg",
    "ch16_12_n12": "16-poraiyudaimai/12-n12_restored_friendship_temple_steps.jpg",
    "ch16_13_n13": "16-poraiyudaimai/13-n13_patient_counselor_with_stubborn_fool.jpg",
    "ch16_14_n14": "16-poraiyudaimai/14-n14_iron_pillar_withstanding_monsoon_gusts.jpg",
    "ch16_15_n15": "16-poraiyudaimai/15-n15_compassionate_guidance_of_errant_child.jpg",
    "ch16_16_n16": "16-poraiyudaimai/16-n16_quiet_strength_in_village_assembly.jpg",
    "ch16_17_n17": "16-poraiyudaimai/17-n17_deep_lake_absorbing_thrown_stone.jpg",
    "ch16_18_n18": "16-poraiyudaimai/18-n18_venerable_teacher_with_unruly_students.jpg",
    "ch16_19_n19": "16-poraiyudaimai/19-n19_granite_temple_standing_centuries.jpg",
    "ch16_20_n20": "16-poraiyudaimai/20-n20_monarch_granting_pardon_to_rebels.jpg",
    "ch16_21_n21": "16-poraiyudaimai/21-n21_ancient_olive_tree_bearing_fruit.jpg",
    "ch16_22_n22": "16-poraiyudaimai/22-n22_scholar_inscribing_virtue_on_copper.jpg",
    "ch16_23_n23": "16-poraiyudaimai/23-n23_sunrise_over_timeless_hills.jpg",
    "ch16_24_n24": "16-poraiyudaimai/24-n24_noble_statue_unmoved_by_birds.jpg",
    "ch16_25_n25": "16-poraiyudaimai/25-n25_goldsmith_testing_gold_touchstone.jpg",
    "ch16_26_n26": "16-poraiyudaimai/26-n26_hasty_wrathful_man_derided_by_crowd.jpg",
    "ch16_27_n27": "16-poraiyudaimai/27-n27_casket_of_pure_gems_opened.jpg",
    "ch16_28_n28": "16-poraiyudaimai/28-n28_elders_honoring_the_patient_peacemaker.jpg",
    "ch16_29_n29": "16-poraiyudaimai/29-n29_pure_pearl_drawn_from_ocean.jpg",
    "ch16_30_n30": "16-poraiyudaimai/30-n30_peaceful_haven_amidst_storm.jpg",
    "ch16_31_n31": "16-poraiyudaimai/31-n31_short_lived_hollow_triumph_of_spite.jpg",
    "ch16_32_n32": "16-poraiyudaimai/32-n32_timeless_song_of_the_forgiving_hero.jpg",
    "ch16_33_n33": "16-poraiyudaimai/33-n33_memorial_hero_stone_with_palm_shade.jpg",
    "ch16_34_n34": "16-poraiyudaimai/34-n34_epigraph_recording_peace_treaty.jpg",
    "ch16_35_n35": "16-poraiyudaimai/35-n35_starry_night_over_ancient_city.jpg",
    "ch16_36_n36": "16-poraiyudaimai/36-n36_children_learning_of_magnanimity.jpg",
    "ch16_37_n37": "16-poraiyudaimai/37-n37_sandalwood_tree_perfuming_axe.jpg",
    "ch16_38_n38": "16-poraiyudaimai/38-n38_physician_dressing_enemy_wounds.jpg",
    "ch16_39_n39": "16-poraiyudaimai/39-n39_giving_sweet_water_to_the_insolent.jpg",
    "ch16_40_n40": "16-poraiyudaimai/40-n40_returning_lost_cattle_to_rival.jpg",
    "ch16_41_n41": "16-poraiyudaimai/41-n41_planting_fruit_trees_on_border.jpg",
    "ch16_42_n42": "16-poraiyudaimai/42-n42_lighting_lamp_for_estranged_kin.jpg",
    "ch16_43_n43": "16-poraiyudaimai/43-n43_insolent_man_hanging_head_in_shame.jpg",
    "ch16_44_n44": "16-poraiyudaimai/44-n44_mirror_of_unbroken_peace.jpg",
    "ch16_45_n45": "16-poraiyudaimai/45-n45_cool_snow_quenching_embers.jpg",
    "ch16_46_n46": "16-poraiyudaimai/46-n46_aggressor_dropping_weapons.jpg",
    "ch16_47_n47": "16-poraiyudaimai/47-n47_reformed_offender_seeking_pardon.jpg",
    "ch16_48_n48": "16-poraiyudaimai/48-n48_crowd_murmuring_respect_for_patience.jpg",
    "ch16_49_n49": "16-poraiyudaimai/49-n49_austere_ascetic_on_mountain_peak.jpg",
    "ch16_50_n50": "16-poraiyudaimai/50-n50_humble_householder_absorbing_revilement.jpg",
    "ch16_51_n51": "16-poraiyudaimai/51-n51_scales_weighing_fasting_vs_forbearance.jpg",
    "ch16_52_n52": "16-poraiyudaimai/52-n52_pure_radiance_of_patient_soul.jpg",
    "ch16_53_n53": "16-poraiyudaimai/53-n53_monsoon_downpour_unmoved_lotus.jpg",
    "ch16_54_n54": "16-poraiyudaimai/54-n54_saintly_presence_calming_village.jpg",
    "ch16_55_n55": "16-poraiyudaimai/55-n55_hermit_abstaining_from_food.jpg",
    "ch16_56_n56": "16-poraiyudaimai/56-n56_hero_swallowing_his_own_anger.jpg",
    "ch16_57_n57": "16-poraiyudaimai/57-n57_cooling_stream_in_forest_sanctuary.jpg",
    "ch16_58_n58": "16-poraiyudaimai/58-n58_sacred_bull_calmly_resting.jpg",
    "ch16_59_n59": "16-poraiyudaimai/59-n59_open_heavens_above_patient_earth.jpg",
    "ch16_60_n60": "16-poraiyudaimai/60-n60_community_celebrating_in_reconciliation.jpg",
    "ch16_61_n61": "16-poraiyudaimai/61-n61_temple_gopuram_against_setting_sun.jpg",
    "ch16_62_n62": "16-poraiyudaimai/62-n62_eternal_flame_in_granite_sanctum.jpg",
}

def sync_artworks():
    copied = 0
    for key, rel_dest in MAPPINGS.items():
        candidates = sorted(ARTIFACT_DIR.glob(f"{key}*.jpg"), key=lambda p: p.stat().st_mtime, reverse=True)
        if candidates:
            src = candidates[0]
            dest = PRODUCTION_VISUALS / rel_dest
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
            copied += 1
    print(f"\nTotal synced Vedic artworks: {copied} / {len(MAPPINGS)}")

if __name__ == "__main__":
    sync_artworks()

